1\. **PCA on 3D dataset**

* Generate a dataset with 3 features each with N entries (N being ${\cal O}(1000)$). With $N(\mu,\sigma)$ the normali distribution with mean $\mu$ and $\sigma$  standard deviation, generate the 3 variables $x_{1,2,3}$ such that:
    * $x_1$ is distributed as $N(0,1)$
    * $x_2$ is distributed as $x_1+N(0,3)$
    * $x_3$ is given by $2x_1+x_2$
* Find the eigenvectors and eigenvalues of the covariance matrix of the dataset
* Find the eigenvectors and eigenvalues using SVD. Check that the two procedures yield to same result
* What percent of the total dataset's variability is explained by the principal components? Given how the dataset was constructed, do these make sense? Reduce the dimensionality of the system so that at least 99% of the total variability is retained.
* Redefine the data in the basis yielded by the PCA procedure
* Plot the data points in the original and the new coordiantes as a set of scatter plots. Your final figure should have 2 rows of 3 plots each, where the columns show the (0,1), (0,2) and (1,2) proejctions.


In [24]:
from matplotlib import pyplot as plt
from scipy import linalg as la
import numpy.random as npr
import numpy as np


# construct a dataset with a skewed 3D distribution
mu = 0  
sigma1 = 1
sigma2 = 3 
n = 1000


x1 = npr.normal(loc=mu, scale=sigma1, size=n)
x2 = x1 + npr.normal(mu, sigma2, n)
x3 = 2*x1 + x2

data = np.array([x1,x2,x3])

#Compute the covariance matrix
cov = np.cov(data)
#Find eigenvectors and eigenvalues of a matrix
l, V = la.eigh(cov)
print("Eigenvalues: ", l)
print("Eigenvectors: ", V)

#????????????????
#Eigenvalues and Eigenvactors using SVD
# Compute the SVD of data
U, s, V2 = la.svd(data)

# The eigenvectors of data(dataT)=cov(data) are the columns of the matrix U
eigenvectors = U

# The eigenvalues of data(dataT)=cov(data) are the squares of the singular values s
eigenvalues = np.square(s)

print("Eigenvectors:", eigenvectors)
print("Eigenvalues:", eigenvalues)
#?????????????????



Eigenvalues:  [-6.54967134e-16  2.10147319e+00  2.64084416e+01]
Eigenvectors:  [[ 0.81649658  0.56446479 -0.12129648]
 [ 0.40824829 -0.71302203 -0.57002887]
 [-0.40824829  0.41590754 -0.81262184]]
Eigenvectors: [[-0.12139551  0.5644435  -0.81649658]
 [-0.56990378 -0.71312202 -0.40824829]
 [-0.81269479  0.41576498  0.40824829]]
Eigenvalues: [2.64087948e+04 2.10005057e+03 9.97090632e-29]


2\. **PCA on a nD dataset**

Start from the dataset you have genereted in the previous exercise and add uncorrelated random noise. Such noise should be represented by other 10 uncorrelated variables normal distributed, with standar deviation much smaller (say, a factor 50) than those used to generate the $x_1$ and $x_2$.

Repeat the PCA procedure and compare the results with what you obtained before

3 \. **Looking at an oscillating spring** (optional)

Imagine you have $n$ cameras looking at a spring oscillating along the $x$ axis. Each  camera record the motion of the spring looking at it along a given direction defined by the pair $(\theta_i, \phi_i)$, the angles in spherical coordinates. 

Start from the simulation of the records (say ${\cal O}(1000)$) of the spring's motion along the x axis, assuming a little random noise affects the measurements along the $y$. Rotate such dataset to emulate the records of each camera.

Perform a Principal Component Analysis on the thus obtained dataset, aiming at finding the only one coordinate that really matters.


4\. **PCA on the MAGIC dataset** (optional)

Perform a PCA on the magic04.data dataset

In [ ]:
# get the dataset and its description on the proper data directory
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.data -P ~/data/
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/magic/magic04.names -P ~/data/ 